on: [push]

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: 
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: fmt (nightly)
        uses: actions-rs/cargo@v1
        if: matrix.rust == 'nightly'
        with:
          command: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings
